# Generated by Django 4.1 on 2023-04-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=10)),
                ('finder_name', models.CharField(max_length=20)),
                ('found_time', models.DateTimeField()),
                ('found_latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='緯度')),
                ('found_longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, verbose_name='経度')),
            ],
        ),
    ]
