# Generated by Django 4.1 on 2023-05-16 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('find_my_lost_property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostproperty',
            name='found_latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='lostproperty',
            name='found_longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=20, verbose_name='経度'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
