# Generated by Django 4.1 on 2023-05-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find_my_lost_property', '0005_lostproperty_dummy_image1_lostproperty_dummy_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostproperty',
            name='manage_location',
            field=models.CharField(default='location', max_length=30),
            preserve_default=False,
        ),
    ]
